version: '3.7'
services:
  web:
    image: ogurliev02/user_service:user_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_user
      - POSTGRES_DB=test

volumes:
  postgres_data: